name: Deploy Playwright report to GitHub Pages

on:
  push:
    branches: [main]
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      API_BASE_URL: ${{ secrets.API_BASE_URL }}
      API_TOKEN: ${{ secrets.API_TOKEN }}
      SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
      REPORT_URL: https://${{ github.repository_owner }}.github.io/${{ github.event.repository.name }}/
      TZ: America/Bogota
      NODE_ENV: production
      PW_JSON: playwright-report/json-report.json
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: npm
      - run: npm ci
      - run: npx playwright install --with-deps
      - run: npx playwright test || true
      - run: touch playwright-report/.nojekyll
      - uses: actions/upload-pages-artifact@v3
        with:
          path: playwright-report
      - name: Send Slack summary
        if: always()
        run: node scripts/slack-report.js
        env:
          API_BASE_URL: ${{ secrets.API_BASE_URL }}
          API_TOKEN: ${{ secrets.API_TOKEN }}
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
          REPORT_URL: https://${{ github.repository_owner }}.github.io/${{ github.event.repository.name }}/
          TZ: America/Bogota
          NODE_ENV: production
          PW_JSON: playwright-report/json-report.json

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - id: deployment
        uses: actions/deploy-pages@v4
